name: Tests

on:
    pull_request:
    push:
        branches:
            - master
        tags:
            - '*'

jobs:
    tests:

        name: Tests
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            # https://github.com/shivammathur/setup-php#tada-php-support
            php-versions: [
              '7.2',
              '7.3',
              '7.4',
              '8.0',
              '8.1',
              ]

        steps:

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php-versions }}

            - name: before_install
              run: |
                mkdir -p "$HOME/bin"
                export PATH="$HOME/bin:$PATH"
                if [ ! -d "$HOME/.phive" ]; then mkdir "$HOME/.phive"; fi
                if [ ! -f "$HOME/.phive/phive.phar" ]; then ant getphive; mv phive.phar "$HOME/.phive/"; fi
                install --mode=0755 -T "$HOME/.phive/phive.phar" "$HOME/bin/phive"

            - name: install
              run: |
                ant setup

            - name: script
              run: |
                ./tools/phpunit

            - name: Cache multiple paths
              uses: actions/cache@v2
              with:
                path: |
                  $HOME/.phive
                  $HOME/.phive/phars
                  $HOME/.cache/composer
                  $HOME/.composer/cache
                  $HOME/.gnupg
                key: ${{ runner.os }}-${{ hashFiles('**/composer.lock','**/phive.xml') }}